Remove the `path_t21` parameter from `ADF_Result.__init__()` (#194)
The ``ADF_Result`` currently takes an extra parameter (compared to all other ``Result`` classes) by the name of ``path_t21``. This extra argument is not accounted from whenever a job crashes, thus causing problems in the lines of code below (_i.e._ it raises a ``TypeError: __init__() missing 1 required positional argument: 'path_t21'``). https://github.com/SCM-NV/qmflows/blob/5e8a2259b3bbcf532099373768fe07537377a415/src/qmflows/packages/packages.py#L346-L369

The herein implemented solution does the following two things:
* Remove the ``path_t21`` parameter from ``ADF_Result.__init__()``.
* Internally construct the tape21 path using the ``plams_dir`` parameter, similar to how ``DFTB_Result.__init__()`` does it.